spring:
  application:
    name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/timezone?useSSL=false&serverTimezone=UTC
    username: root
    password: MysqlLogin_19
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}




logging:
  pattern:
    console: "%msg%n"
#  level:
#    org.springframework.web: DEBUG
#    org.hibernate: DEBUG
#    com.netflix.eureka: DEBUG
#    com.netflix.discovery: DEBUG
#
